export const TERMINAL_NUMBERS = [
  { id: 'term1', label: 'T1', value: '+993 61 772671' },
  { id: 'term2', label: 'T2', value: '+993 64 614588' },
]

export const PHONE_NUMBERS = [
  '+993 61 772671',
  '+993 64 614588',
  '+993 71 007821',
  '+993 71 007549',
  '+993 62 797869',
  '+993 61 023224',
  '+993 63 606592',
  '+993 62 797284',
  '+993 65 303785',
]

export const TRANSLATIONS = {
  tk: {
    badge: 'Töleg Hyzmaty',
    heroDesc: 'Aşakdan töleg usulyny saýlaň we tölegi tamamlaň',
    tabTerm: 'Terminal Arkaly Töleg',
    tabTermSub: '2 terminal nomer',
    tabPhone: '0804 Arkaly Töleg',
    tabPhoneSub: '9 telefon nomer',
    termTag: 'Terminal Töleg',
    termTitle: 'Terminal Nomerini Saýlaň',
    termHint: 'Aşakdaky terminal nomerlerinden birini saýlaň, kopýa ediň we terminaldaky tölegi geçiriň.',
    termInfo: 'Tölegi tamamlanyňyzdan soň tassyklaýjy çegiň suratyny admine iberiň.',
    phoneTag: '0804 Töleg',
    phoneTitle: 'Telefon Nomerini Saýlaň',
    phoneHint: 'Aşakdaky nomerlerden birine <strong>0804</strong> arkaly pul iberiň.',
    phoneInfo: 'Tölegden soň <strong>0801</strong>-den gelen çegiň suratyny admine ugradyň.',
    copy: 'Kopya et',
    pay: '💸 Töle',
    copied: 'Kopýa edildi!',
  },
  ru: {
    badge: 'Платёжный Сервис',
    heroDesc: 'Выберите способ оплаты ниже и завершите транзакцию',
    tabTerm: 'Оплата через терминал',
    tabTermSub: '2 номера терминала',
    tabPhone: 'Оплата через 0804',
    tabPhoneSub: '9 телефонных номеров',
    termTag: 'Терминал',
    termTitle: 'Выберите номер терминала',
    termHint: 'Скопируйте один из номеров терминала ниже и проведите оплату.',
    termInfo: 'После оплаты отправьте фото чека администратору.',
    phoneTag: 'Оплата 0804',
    phoneTitle: 'Выберите номер телефона',
    phoneHint: 'Переведите деньги на один из номеров ниже через <strong>0804</strong>.',
    phoneInfo: 'После оплаты отправьте фото чека с <strong>0801</strong> администратору.',
    copy: 'Копировать',
    pay: '💸 Оплатить',
    copied: 'Скопировано!',
  },
  tr: {
    badge: 'Ödeme Hizmeti',
    heroDesc: 'Aşağıdan ödeme yöntemini seçin ve işlemi tamamlayın',
    tabTerm: 'Terminal ile Ödeme',
    tabTermSub: '2 terminal numarası',
    tabPhone: '0804 ile Ödeme',
    tabPhoneSub: '9 telefon numarası',
    termTag: 'Terminal Ödeme',
    termTitle: 'Terminal Numarasını Seçin',
    termHint: 'Aşağıdaki terminal numaralarından birini kopyalayın ve ödemeyi gerçekleştirin.',
    termInfo: 'Ödeme sonrası onay makbuzunu admine gönderin.',
    phoneTag: '0804 Ödeme',
    phoneTitle: 'Telefon Numarasını Seçin',
    phoneHint: 'Aşağıdaki numaralardan birine <strong>0804</strong> üzerinden para gönderin.',
    phoneInfo: "Ödeme sonrası <strong>0801</strong>'den gelen makbuz fotoğrafını admine gönderin.",
    copy: 'Kopyala',
    pay: '💸 Öde',
    copied: 'Kopyalandı!',
  },
}
